version: '3.7'
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.6-standalone
    ports:
      - 8080:8080
