version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: yarn
          command: yarn
      - run:
          name: build
          command: yarn build
  build-backend:
    docker:
      - image: ocaml/opam2:4.08
        environment:
          TERM: xterm
      - image: postgres:12.2
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
    steps:
      - run:
          name: Update opam
          command: |
            opam remote remove --all default
            opam remote add default https://opam.ocaml.org
      - checkout
      - run:
          name: Pin sihl packages
          command: |
            # TODO remove this once sihl is in OPAM
            opam pin add -y -n sihl https://github.com/oxidizing/sihl.git\#0.0.28
            opam pin add -y -n sihl_repo_postgresql https://github.com/oxidizing/sihl.git\#0.0.28
            opam pin add -y -n sihl_email https://github.com/oxidizing/sihl.git\#0.0.28
            opam pin add -y -n sihl_email_repo_postgresql https://github.com/oxidizing/sihl.git\#0.0.28
            opam pin add -y -n sihl_user https://github.com/oxidizing/sihl.git\#0.0.28
            opam pin add -y -n sihl_user_repo_postgresql https://github.com/oxidizing/sihl.git\#0.0.28
      - run:
          name: Pin packages
          command: |
            opam pin add -y -n sihl_example_issues .
      - run:
          name: Install system dependencies
          command: |
            opam depext -y sihl_example_issues
      - run:
          name: Install OCaml dependencies
          command: opam install --deps-only -y sihl_example_issues
      - run:
          name: Build
          command: opam config exec -- make
      - run:
          name: Install OCaml test dependencies
          command: opam install -y alcotest alcotest-lwt cohttp-lwt-unix
      - run:
          name: Test
          command: opam config exec -- make test
  deploy:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Add SSH host
          command: |
            mkdir -p ~/.ssh
            echo "88.198.48.243 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0oq45ku/Xo14ow1jry+eo/qVHOKVXRQfQCIAVnco2Wwy0TlZf/SYAK3jIRdm3/5a9DbEcqM28ISZ3ZX+0v6ov0hmmHdx8pdx3AlRvgHOpjcpqvCIIM1rU4ZnXb9LAd9ICx49O26Ns5kYEsNVSWVdCKVt3rMM9BO0Oe0OClRKPkr/D69HU7Jhu7ZacmmWoTrcABQthVSt/0AYyLKxc9BtmL0dS2zCCbiSJD9CeEcScK1FVzBJacbyx5mVEypp6wjbNNKAR5AThMkSH7tXnrSnSkguJfKjoy4M79RhtRtuOrDOGQmIwA6GzqdMrcBSj0ACCO1LmB83BXhi0QfpzGTwX" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "23:77:b3:08:3c:5f:4c:6c:8c:35:11:be:2d:de:ed:00"
      - run:
          name: Install git
          command: |
            apt-get update -y
            apt-get install -y git
      - run:
          name: Deploy
          command: |
            git remote add dokku dokku@88.198.48.243:sihl-example-issues
            git push -f dokku master

workflows:
  version: 2
  build:
    jobs:
      - build-frontend
      - build-backend
      - deploy:
          requires:
            - build-frontend
            - build-backend
          filters:
            branches:
              only:
                - master
